awsbites/aws-bites-site

- src/_transcripts/54.json
- src/episodes/60-what-is-lambda.md
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/54.json
> add episode 54 transcript

- src/_transcripts/47.json
- src/episodes/60-what-is-lambda.md
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/47.json
> add episode 47 transcript

- src/_transcripts/46.json
- src/episodes/60-what-is-lambda.md
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/46.json
> add episode 46 transcript

- src/_transcripts/1.json
- src/episodes/60-what-is-lambda.md
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/1.json
> add episode 1 transcript

- src/_transcripts/44.json
- src/episodes/60-what-is-lambda.md
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/44.json
> add episode 44 transcript

- src/_transcripts/2.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/2.json
> add episode 2 transcript

- src/_transcripts/4.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/4.json
> add episode 4 transcript

- src/_transcripts/42.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/42.json
> add episode 42 transcript

- src/_transcripts/48.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/48.json
> add episode 48 transcript

- src/_transcripts/7.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/7.json
> add episode 7 transcript

- src/_transcripts/55.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/55.json
> add episode 55 transcript

- src/_transcripts/3.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/3.json
> add episode 3 transcript

- src/_transcripts/11.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/11.json
> add episode 11 transcript

- src/_transcripts/6.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/6.json
> add episode 6 transcript

- src/_transcripts/9.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/9.json
> add episode 9 transcript

- src/_transcripts/8.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/8.json
> add episode 8 transcript

- src/_transcripts/62.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/62.json
> add episode 62 transcript

- src/_transcripts/63.json
ironically, this episode's transcript seemed to need a lot of fixes! 😳
> Fix up 63 transcript

- src/_transcripts/64.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/64.json
> add episode 64 transcript

- src/_transcripts/65.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/65.json
> add episode 65 transcript

- src/_transcripts/67.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/67.json
> add episode 67 transcript

- src/_transcripts/68.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/68.json
> add episode 68 transcript

- src/_transcripts/69.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/69.json
> add episode 69 transcript

- src/_transcripts/71.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/71.json
> add episode 71 transcript

- src/_transcripts/72.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/72.json
> add episode 72 transcript

- src/_transcripts/73.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/73.json
> add episode 73 transcript

- src/_transcripts/74.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/74.json
> add episode 74 transcript

- src/_transcripts/75.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/75.json
> add episode 75 transcript

- src/_transcripts/76.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/76.json
> add episode 76 transcript

- src/_transcripts/77.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/77.json
> add episode 77 transcript

- src/_transcripts/78.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/78.json
> add episode 78 transcript

- src/_transcripts/80.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/80.json
> add episode 80 transcript

- src/_transcripts/81.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/81.json
> add episode 81 transcript

- src/_transcripts/82.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/82.json
> add episode 82 transcript

- src/_transcripts/83.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/83.json
> add episode 83 transcript

- src/_transcripts/84.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/84.json
> add episode 84 transcript

- src/_transcripts/85.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/85.json
> add episode 85 transcript

- src/_transcripts/86.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/86.json
> add episode 86 transcript

- src/_transcripts/87.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/87.json
> add episode 87 transcript

- src/_transcripts/89.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/89.json
> add episode 89 transcript

- src/_transcripts/90.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/90.json
> add episode 90 transcript

- src/_transcripts/92.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/92.json
> add episode 92 transcript

- src/_transcripts/93.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/93.json
> add episode 93 transcript

- src/_transcripts/95.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/95.json
> add episode 95 transcript

- src/_transcripts/96.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/96.json
> add episode 96 transcript

- src/_transcripts/97.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/97.json
> add episode 97 transcript

- src/_transcripts/98.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/98.json
> add episode 98 transcript

- src/_transcripts/99.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/99.json
> add episode 99 transcript

- src/_transcripts/100.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/100.json
> add episode 100 transcript

- src/_transcripts/101.json
Automatic pull request created from s3://pod-transcription-935672627075-eu-west-1/processed-transcripts/101.json
> add episode 101 transcript

- src/_transcripts/102.json
In this episode, we have the pleasure of speaking with Jeremy Daly, CEO of AMPTH and a leader in the AWS and serverless community. We discuss Jeremy's journey into AWS and serverless, the prolific open source work and content he creates, the evolution of serverless over the years, common myths about serverless, and the story behind building AMPTH to improve the developer experience. Jeremy provides his perspective on the state of serverless and predictions for the future.
00:00 Introduction
01:34 Jeremy's journey into AWS and discovering serverless
06:39 Jeremy's prolific …
> add episode 102 transcript

- src/_transcripts/104.json
- src/_transcripts/104.vtt
In this episode, we celebrate AWS Lambda's 9th birthday by taking a deep dive into Lambda runtimes. We discuss how Lambda works, compare official runtimes vs. custom runtimes, and explain when and why building a custom runtime might be worth the effort. We talk through how custom runtimes work, options for deploying them, and potential use cases where they could be beneficial over standard runtimes.
00:00 Introduction and overview of serverless and AWS Lambda.
00:55 Overview of podcast and sponsors.
01:09 Recapping serverless and AWS Lambda.
01:20 Lambda is an event-based …
> add episode 104 transcript

- src/_transcripts/105.json
- src/_transcripts/105.vtt
In this episode, we discuss integration testing event-driven systems and explore AWS's new Integration Application Test Kit (IATK). We cover the challenges of testing events and common approaches like logging, end-to-end testing, and using temporary queues. We then introduce IATK, walk through how to use it for EventBridge testing, and share our experience trying out the X-Ray trace validation. We found IATK promising but still rough around the edges, though overall a useful addition to help test complex event flows.
00:00 Introduction to integration testing challenges …
> add episode 105 transcript

- src/_transcripts/106.json
- src/_transcripts/106.vtt
- src/episodes/106-luciano-at-reinvent.md
In this episode, Luciano and Eoin have a lively discussion about Luciano's experience attending AWS re:Invent 2023 in Las Vegas for the first time. They talk about the massive scale of the event, logistical challenges getting around between venues, highlights from the keynotes and announcements, and tips for networking and getting the most out of re:Invent. Luciano shares his perspective on the AI focus, meeting people in real life after connecting online, rookie mistakes to avoid, and why re:Invent is worth the investment for anyone working in the AWS space.
00:00 …
> add episode 106 transcript

- src/_transcripts/108.json
- src/_transcripts/108.vtt
In this episode, we discuss using Python for data science workloads on AWS Lambda. We cover the pros and cons of using Lambda for these workloads compared to other AWS services. We benchmark cold start times and performance for different Lambda deployment options like zip packages, layers, and container images. The results show container images can provide faster cold starts than zip packages once the caches are warmed up. We summarize the optimizations AWS has made to enable performant container image deployments. Overall, Lambda can be a good fit for certain data science …
> add episode 108 transcript

- src/_transcripts/109.json
- src/_transcripts/109.vtt
In this episode, we provide an overview of AWS Project Development Kit (PDK), an open source tool to help bootstrap and maintain projects. We discuss what PDK is, how it can help generate boilerplate code and infrastructure, keep configuration consistent across projects, and some of the pros and cons of using a tool like this vs doing it manually.
00:00 Introduction to topic and speakers
00:59 What is PDK and what problem does it aim to solve?
03:28 How PDK builds on CDK and Progen
04:21 Overview of Progen and how it fits into the ecosystem
07:19 How Progen could be used …
> add episode 109 transcript

- src/_transcripts/111.json
- src/_transcripts/111.vtt
In this episode, we discuss how we work as a cloud consulting company, including our principles, engagement process, sprint methodology, and focus on agile development to deliver successful projects. We aim to be trusted partners, not just vendors, and enable our customers' business goals.
00:00 Introduction to hosts and podcast sponsor
01:41 Background on founding of fourTheorem and focus on quality over quantity
05:04 Discovery session to understand customer's problem space
10:55 How software projects differ from traditional engineering
15:36 Effective software …
> add episode 111 transcript

- src/_includes/episodes_layout.njk
- allow direct links to the transcript to be shared
- keep the open tab persistent when you LiveReload
> feat: allow hash anchors for tabs

- src/_transcripts/114.json
- src/_transcripts/114.vtt
In this episode, we discuss the new experimental AWS Lambda LLRT runtime for JavaScript. We provide an overview of what a Lambda runtime is and how LLRT aims to optimize cold starts and performance compared to existing runtimes like Node.js. We outline the benefits of LLRT but also highlight concerns around its experimental status, lack of parity with Node.js, and reliance on lesser known dependencies like QuickJS. Overall, LLRT shows promise but needs more stability, support, and real-world testing before it can be recommended for production use.
00:00 Introduction to …
> add episode 114 transcript

- src/_transcripts/117.json
- src/_transcripts/117.vtt
In this episode, we provide an overview of Amazon EBS, which stands for Elastic Block Storage. We explain what block storage is and how EBS provides highly available and high performance storage volumes that can be attached to EC2 instances. We discuss the various EBS volume types, including GP3, GP2, provisioned IOPS, and HDD volumes, and explain how they differ in performance characteristics like IOPS and throughput. We go over important concepts like IOPS, throughput, and volume types so listeners can make informed decisions when provisioning EBS. We also cover EBS …
> add episode 117 transcript

- src/_transcripts/118.json
- src/_transcripts/118.vtt
In this episode, we provide an introductory overview of AWS best practices for managing infrastructure using multiple accounts under an organization. We discuss the advantages of this approach and how to get started creating your own multi-account environment, or "landing zone".
00:00 Introduction to topic of using multiple AWS accounts and setting up a landing zone.
01:25 Definition and benefits of using a multi-account AWS landing zone.
02:01 Key advantages of using multiple AWS accounts, including isolation, access controls, and cost optimization.
07:14 Recommendations …
> add episode 118 transcript

- src/_transcripts/119.json
- src/_transcripts/119.vtt
In this episode, we provide commentary and analysis on the 2024 AWS Community Survey results. We go through the key findings for each area including infrastructure as code, CI/CD, serverless, containers, NoSQL databases, event services, and AI/ML. While recognizing potential biases, we aim to extract insights from the data and share our perspectives based on experience. Overall, we see increased adoption across many services, though some pain points remain around developer experience. We hope this format provides value to listeners interested in cloud technology trends. …
> add episode 119 transcript

- src/_transcripts/120.json
- src/_transcripts/120.vtt
In this episode, we discuss best practices for working with AWS Lambda. We cover how Lambda functions work under the hood, including cold starts and warm starts. We then explore different invocation types - synchronous, asynchronous, and event-based. For each, we share tips on performance, cost optimization, and monitoring. Other topics include function structure, logging, instrumentation, and security. Throughout the episode, we aim to provide a solid mental model for serverless development and share our experiences to help you build efficient and robust Lambda …
> add episode 120 transcript

- src/_transcripts/123.json
- src/_transcripts/123.vtt
In this longer episode, we provide a comprehensive overview of DynamoDB, including how it compares to relational databases, when to use it, how to get started, writing and querying data, secondary indexes, and single table design. We share our experiences using DynamoDB and discuss the pros and cons compared to traditional SQL databases.
00:00 Introduction to the episode on DynamoDB
00:38 Podcast sponsor message
00:53 Comparing DynamoDB and relational databases
06:32 DynamoDB terminology and concepts
09:44 When and why to use DynamoDB
16:03 How DynamoDB partitions and …
> add episode 123 transcript

- src/_transcripts/126.json
- src/_transcripts/126.vtt
In this episode, we discuss solutions for securely accessing private VPC resources for debugging and troubleshooting. We cover traditional approaches like bastion hosts and VPNs, as well as newer solutions using containers and AWS services like Fargate, ECS, and SSM. We explain how to set up a Fargate task with a container image that has the necessary tools, enable ECS integration with SSM, and use SSM to start remote shells and port forwarding tunnels into the container. This provides on-demand access without exposing resources publicly. We share a Python script to …
> add episode 126 transcript

- src/_transcripts/130.json
- src/_transcripts/130.vtt
In this episode, we had the pleasure to interview Farah Campbell, head of modern compute community at AWS, prolific speaker, and former AWS Hero. We discussed Farah's career journey from healthcare into tech, tips on public speaking, dealing with imposter syndrome, the pace of innovation in cloud, and predictions for the future. Farah shared personal stories and advice for getting started in tech and being an active member of the community. It was inspiring to hear from someone so passionate about helping others learn and grow.
00:56 Introduction and welcoming Farah to the …
> add episode 130 transcript

- src/_transcripts/132.json
- src/_transcripts/132.vtt
- src/episodes/132-github-action-runners.md
In this episode, we provided an overview of GitHub Action Runners and discussed the benefits of using self-hosted runners on AWS. We covered options like EC2, CodeBuild, and Lambda for running GitHub Actions, compared pricing across solutions, and shared our hands-on experience setting things up. Overall, using AWS services can provide more control, lower latency, and cost optimization compared to GitHub hosted runners.
00:04 Introduced GitHub Actions and runners that execute workflow jobs
00:38 AWS Bites sponsor message
00:48 Asked what are GitHub Action runners and how …
> add episode 132 transcript

- src/_transcripts/133.json
- src/_transcripts/133.vtt
- src/episodes/133-fiona-mckenna.md
In this special episode of AWS Bites, Eoin is joined by Fiona McKenna, co-founder and CFO of 4Theorem, to discuss startup advice, hiring and growing teams, creating an environment for success, and managing cloud costs. They cover important themes around people, culture, leadership, and finance from Fiona's extensive experience in the tech industry.
00:03 Introduction of hosts and guest Fiona McKenna
00:15 Fiona's background and experience in tech startups
02:28 Advice on hiring and growing teams
06:00 Challenges in recruiting the right people
09:06 Advice for startups …
> add episode 133 transcript

- src/_transcripts/135.json
In this episode, we discuss the pros and cons of using serverless architecture in enterprise companies. We cover topics like cost, complexity, security, ability to evolve architecture, and more. Overall, we find that serverless can provide benefits like reduced operational costs, improved developer productivity, and increased focus on core business logic for larger companies, despite some limitations around unit cost of compute.
00:00 Introduction
00:43 Podcast sponsor ad
00:52 Definition and traits of serverless architecture
02:21 Addressing some common criticisms of …
> add episode 135 transcript

- src/_data/settings.js
- src/index.njk
Update copy on meta tags and the Home Page
> feat: copy updates

- src/_transcripts/136.json
- src/_transcripts/136.vtt
In this pre-re:Invent 2022 episode, Luciano and Eoin discuss some of their favorite recent AWS announcements, including improvements to AWS Step Functions, Lambda runtime updates, DynamoDB and S3 price reductions, ALB header injection, Cognito enhancements, VPC public access blocking, and more. They share their thoughts on the implications of these new capabilities and look forward to seeing what else is announced at the conference. Overall, it's an exciting time for AWS developers with many new features to explore.
00:00 Introduction
00:23 Overview of announcements to be …
> add episode 136 transcript

- src/_transcripts/137.json
- src/_transcripts/137.vtt
- src/episodes/137-transit-gateway.md
In this episode, we provide an overview of AWS Transit Gateway, which aims to simplify complex network connectivity between VPCs, VPNs, and on-premises networks. We discuss the limitations of using VPC peering and the benefits Transit Gateway provides through its hub-and-spoke model. The main components of Transit Gateway are explained, including attachments, route tables, associations, and route propagation. We go through some example use cases like sharing Transit Gateways across accounts, network isolation for compliance, routing traffic through security services, and …
> add episode 137 transcript

- src/_transcripts/138.json
- src/_transcripts/138.vtt
In this episode, we provide guidance for aspiring cloud architects by sharing our personal journeys and outlining the technical and soft skills required. We map a practical roadmap with online courses, hands-on projects, and community resources. Our advice: be patient, keep learning and growing, and remember architecting is an ongoing adventure!
00:04 We introduce the episode topic: becoming a cloud architect.
02:45 We discuss motivations and opportunities in cloud architecture.
03:56 We define the role and responsibilities of a cloud architect.
10:08 We examine whether …
> add episode 138 transcript

- src/_includes/base.njk
- src/_includes/episodes_layout.njk
- src/episodes/139-powertools-api.md
- src/index.njk
- **feat: add BSky, LinkedIn to episode**
- **chore: move eoin socials Twatter -> BlueSky**
> tweak episode socials

- src/_transcripts/141.json
- src/_transcripts/141.vtt
In this episode, we provide an overview of AWS Step Functions and dive deep into the powerful new JSONata and variables features. We explain how JSONata allows complex JSON transformations without custom Lambda functions, enabling more serverless workflows. The variables feature also helps avoid the previous 256KB state size limit. We share examples from real projects showing how these features simplify workflows, reduce costs and enable new use cases.
00:00 Introduction and recap of step functions
00:55 Overview of what step functions are and key capabilities
06:31 …
> add episode 141 transcript

- src/_transcripts/142.json
- src/_transcripts/142.vtt
- src/episodes/142-escape-from-s3.md
We discuss common use cases and challenges for copying data between S3 buckets and S3-compatible object storage services. We share our experience building an open source Node.js CLI tool called S3-Migrate to efficiently migrate data with separate source and destination credentials. We cover performance considerations like streaming, chunk sizes, concurrency and parallelism.
00:00 Introduction to copying data between S3 and S3-compatible storage
01:49 Overview of competitive S3-compatible storage options
02:17 Challenges using AWS CLI s3 sync across storage providers
04:59 …
> add episode 142 transcript

- src/_transcripts/143.json
- src/_transcripts/143.vtt
- src/episodes/143-is-app-runner-better-than-fargate.md
In this episode, we share our experience migrating a containerized web application to AWS AppRunner. We discuss the pros and cons of AppRunner compared to alternatives like Fargate, covering topics like ease of use, networking, logging, custom domains, pricing, and more. Overall, AppRunner provides a simple way to deploy containers without managing infrastructure, but has some limitations around customization that may make alternatives like Fargate better for more complex use cases.
00:00 Introduction to AppRunner and the use case we migrated
01:23 Comparing AppRunner to …
> add episode 143 transcript

- src/_transcripts/145.json
In this episode, we dive into Amazon Aurora Serverless v2, also known as DSQL. We discuss the pros and cons of DSQL, including its ease of use, scalability, availability, and limitations compared to a traditional PostgreSQL database. We walk through a code example using Node.js, TypeScript, and the Drizzle ORM, explaining how we load tested DSQL and analyzed performance metrics in X-Ray. We also cover high availability configurations, multi-region setup, and examine the pricing model. Overall, DSQL shows promise as a fully managed PostgreSQL compatible database, but may …
> add episode 145 transcript

- src/_transcripts/147.json
- src/_transcripts/147.vtt
- src/episodes/147-spec-coding-with-kiro.md
In this episode, we provide an overview of Kiro, the new AI-powered IDE from AWS. We discuss the key features like the spec-driven development approach, which helps guide you through the process of defining requirements, design, and implementation tasks before writing any code. We share our hands-on experience trying Kiro on a real project, what worked well, and some of the limitations we encountered since it's still in beta. We also cover the pricing model and get into a discussion around whether AWS seems fully committed to making Kiro a success. Overall, we see …
> add episode 147 transcript

- src/_transcripts/148.json
- src/_transcripts/148.vtt
- src/_transcripts/149.json
- src/episodes/148-lambda-and-java.md
In this episode, we discuss whether Java is too old for serverless and can handle the scale of Lambda. We are joined by Mark Sailes, an expert on Java and serverless. Mark shares his experience helping large companies adopt serverless and explains when Java is the right choice for Lambda. We cover optimizing Java Lambda functions, tools and techniques to reduce cold starts, using frameworks like Spring and Quarkus, testing locally vs. in the cloud, and more. Mark emphasizes meeting teams where they are, choosing the right tech based on their skills, and helping enterprises …
> add episode 148 transcript

- src/_transcripts/149.json
- src/_transcripts/149.vtt
- src/episodes/149-headless-cms.md
We dive deep into Strapi, an open-source headless CMS that's changing how we approach content management and CRUD applications. In this episode, we explore how Strapi separates content from presentation, allowing marketing teams to manage content independently while developers maintain full control over the frontend experience. We discuss the powerful features that caught our attention, including the visual content type builder, dynamic zones, components, and the innovative blocks editor that stores content as JSON rather than HTML. We also cover practical aspects like …
> add episode 149 transcript
